### ISSUE TITLE
had to tweak http request for browser app

### ISSUE THREAD

**Issue by ultralame** [austinkelleher/giphy-api#1]
i was getting the following error when using `giphy.search()` in a browser app.
```
XMLHttpRequest cannot load http://api.giphy.com/v1/gifs/search?q=asdf&api_key=dc6zaTOxFJmzC.
A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. 
Origin 'http://localhost:3020' is therefore not allowed access.
```
i resolved this by changing the call to `http.get()` to instead take an options object like so.
```
var requestOptions = {
  hostname: 'api.giphy.com',
  port: 80,
  path: '/v1/' + options.api + endpoint + query, 
  withCredentials: false
};

http.get(requestOptions, function(response) { ... }
```
not sure if this is the best solution. posting here in case others run into a similar problem.

**Comment by austinkelleher** [comment]
Thanks! I'll poke at making this more browser friendly soon. PR's welcome.

**Comment by ultralame** [comment]
I can send you a PR with my changes if you want to disable credentials for everyone. Not sure if it would cause issues in people's Node apps. Making it an option would be a bigger task.

**Comment by austinkelleher** [comment]
I think we should explore a more common approach that can be Node and browser friendly.

**Comment by oswaldoacauan** [comment]
Any news on this issue?

Maybe we can check `process.browser` ([see](http://stackoverflow.com/a/27718218)) and disable credentials?
