### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by staminna** [austinkelleher/giphy-api#10]
Hi

I am trying to make render images in jade, and I can open the urls in separate browser windows, but when using insertAdjacentHTML, I can see the browser icons adding up, but inspecting the DOM in the console I can see 403 forbidden error. Here is the response:

<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BB6E832B7178DC18</RequestId>
<HostId>
4cm9AKXA3d/DT7MLGFC6EkHeQuAjiwptzL0Pv82uzdK4ggIPT2y+rFV9cQAHeJOVss0OHFv83cU=
</HostId>
</Error>

I am using the default key, but manually setting the public key, the issue remains the same.

**Comment by austinkelleher** [comment]
Could you please provide a minimal project/example that reproduces this issue?

**Comment by staminna** [comment]
I was using bad javascript. This is fixed. Thank you

**Comment by austinkelleher** [comment]
:+1:
