### ISSUE TITLE
GIPHY short links

### ISSUE THREAD

**Issue by Helmasaur** [austinkelleher/giphy-api#30]
Isn't it implemented in this project or is it GIPHY API which doesn't let us use short links?

**Comment by austinkelleher** [comment]
Hey, @Helmasaur. It looks like Giphy returns:

```
bitly_url: string
The unique bit.ly URL for this GIF
```

*Undocumented:*
```
bitly_gif_url: string
```

But it does not point to the actualy `.gif` file.

**Comment by Helmasaur** [comment]
I took the first GIF on their homepage so when you click on [Copy link](https://giphy.com/gifs/reactionseditor-rad-dodgeball-3o7bu3hxaeqgi9SJQk/links), there is a field called _Short link_ with the value http://gph.is/2tB7gs3 . I guess they don't return it then.

**Comment by austinkelleher** [comment]
I'm going to go ahead and close this out since it's not an issue with this module. Let me know if you have any additional questions. Thanks!
